name: SuperTools
version: ${project.version}
main: me.progamer260.supertools.Main
authors: [Progamer260]
description: Provides a variation of Super Tools
website: https://github.com/Progamer2600
commands:
  supertools:
    description: Opens the SuperTools GUI
